# NumPy Basic

In [ ]:
import numpy as np

### 0차원 스칼라 생성

In [ ]:
a = 1

ar0 = np.array(a)

a # 1
ar0 # array(1)

In [ ]:
type(ar0) # numpy.ndarray
ar0.ndim # 0
ar0.shape # ()
ar0.size # 1
ar0.dtype # dtype('int64')

### 1차원 배열 생성

In [ ]:
li1 = [1, 2.0, '3']

In [ ]:
ar1 = np.array(li1)
ar1 
# li1 = [1, 2, 3] # array([1, 2, 3])
# li1 = [1, 2.0, 3] # array([1., 2., 3.])
# li1 = [1, 2.0, '3'] # array(['1', '2.0', '3'], dtype='<U32')

In [ ]:
type(ar1) # numpy.ndarray
ar1.ndim # 1
ar1.shape # (3,)
ar1.size # 3
ar1.dtype # dtype('<U32')

### 1차원 배열 원소의 자료형 변환

In [ ]:
# ar1.astype(int)
# ValueError: invalid literal for int() with base 10: np.str_('2.0')

# 메서드 체이닝
ar1.astype(float).astype(int).astype(str).astype(int)
# array([1, 2, 3])

### 배열 생성 시 원소 자료형 지정

In [ ]:
np.array(li1, dtype=int) # array([1, 2, 3])
np.array(li1, dtype=float) # array([1., 2., 3.])
np.array(li1, dtype=str) # array(['1', '2.0', '3'], dtype='<U3')

# 앞에있는 object는 np.array 클래스에 정의된 매개변수이고, 뒤에 있는 object는 파이썬 내장 함수
np.array(object=li1, dtype=object) # array([1, 2.0, '3'], dtype=object)

### 간격이 일정한 배열 생성

In [ ]:
np.arange(6) # array([0, 1, 2, 3, 4, 5])
np.arange(1, 6) # array([1, 2, 3, 4, 5])
np.arange(1, 6, 2) # array([1, 3, 5])
np.arange(0, 1, 0.1) # array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])
np.arange(0, 1.1, 0.1) # array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
np.linspace(0, 1, 10+1) # array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### 원소를 반복한 배열 생성

In [ ]:
np.tile(ar1, 2)
# array(['1', '2.0', '3', '1', '2.0', '3'], dtype='<U32')

np.repeat(ar1, 2)
# array(['1', '1', '2.0', '2.0', '3', '3'], dtype='<U32')

np.repeat(ar1, [3, 2, 1])
# array(['1', '1', '1', '2.0', '2.0', '3'], dtype='<U32')

### 1차원 배열 기본 인덱싱

In [ ]:
ar1 = np.arange(1, 12, 2)
ar1 # array([ 1,  3,  5,  7,  9, 11])

ar1[0] # np.int64(1)
ar1[1] # np.int64(3)
ar1[-1] # np.int64(11)

In [ ]:
# 넘파이 버전 2부터 np.int64(n) 형태로 바뀜
# 만약 값만 보고 싶다면 마지막에 item 메서드를 추가
ar1[0].item() # 1

type(ar1[0]) # numpy.int64
type(ar1[0].item()) # int

### 1차원 배열 슬라이싱

In [ ]:
ar1[0:3] # array([1, 3, 5])
ar1[:3] # array([1, 3, 5])
ar1[3:] # array([ 7,  9, 11])
ar1[:] # array([ 1,  3,  5,  7,  9, 11])

### 1차원 배열 고급 인덱싱
- 팬시 인덱싱

In [ ]:
ar1[[3, 1, 2]] # array([7, 3, 5])
ar1[[3, 3, 3]] # array([7, 7, 7])
ar1[[3, 1, 2, 0, 4, 5]] # array([ 7,  3,  5,  1,  9, 11])
ar1[[3, 1, 2, 0, 4, 5, 3, 1, 2, 0, 4, 5]] 
# array([ 7,  3,  5,  1,  9, 11,  7,  3,  5,  1,  9, 11])

- 불리언 인덱싱
    - 불리언 인덱싱의 경우 원본 배열의 원소 개수와 같지 않으면 에러 발생

In [ ]:
ar1[[False, False, False, True, True, True]] # array([ 7,  9, 11])

In [ ]:
# 브로드캐스팅 : 왼쪽 배열 원소 개수만큼 오른쪽 연산자를 확장시켜 원소마다 비교 연산을 수행
ar1[ar1 >= 7] # array([ 7,  9, 11])

### 2차원 배열 생성

In [ ]:
li2 = [[1, 3, 5], [7, 9, 11]]
ar2 = np.array(li2)

ar2
# array([[ 1,  3,  5],
#        [ 7,  9, 11]])

In [ ]:
type(ar2) # numpy.ndarray
ar2.ndim # 2
ar2.shape # (2, 3)
ar2.size # 6
ar2.dtype # dtype('int64')

### 배열의 재구조화

In [ ]:
ar1.reshape(2, 3)
# array([[ 1,  3,  5],
#        [ 7,  9, 11]])

# order 속성 변경
ar1.reshape(2, 3, order='F')
# array([[ 1,  5,  9],
#        [ 3,  7, 11]])

In [ ]:
# -1은 자동 계산
ar2 = ar1.reshape(2, -1)
ar2
# array([[ 1,  3,  5],
#        [ 7,  9, 11]])

ar2 = ar1.reshape(-1, 3)
ar2
# array([[ 1,  3,  5],
#        [ 7,  9, 11]])

- flatten
- ravel

In [ ]:
ar2.flatten()
# array([ 1,  3,  5,  7,  9, 11])

ar2.ravel()
# array([ 1,  3,  5,  7,  9, 11])

### 2차원 배열 인덱싱 및 슬라이싱

In [ ]:
ar2
# array([[ 1,  3,  5],
#        [ 7,  9, 11]])

In [ ]:
# 인덱싱

ar2[0, 0] # np.int64(1)
ar2[0] # array([1, 3, 5])
ar2[:, 0] # array([1, 7])

In [ ]:
# 슬라이싱

ar2[0:2, 0:2]
# array([[1, 3],
#        [7, 9]])
ar2[:, 1:3]
# array([[ 3,  5],
#        [ 9, 11]])
ar2[:, [2, 1]]
# array([[ 5,  3],
#        [11,  9]])

### 배열의 산술 연산과 브로드캐스팅

In [ ]:
ar1 = np.array([[0, 1, 2]])
ar1 # array([[0, 1, 2]])

ar1 + 1 # array([[1, 2, 3]])

In [ ]:
ar2 = ar1.reshape(-1, 1)
ar2
# array([[0],
#        [1],
#        [2]])

ar2 * 2
# array([[0],
#        [2],
#        [4]])

### 수학 관련 속성 및 함수

In [ ]:
ar1 = np.array([1, 4, 3, 5, 2, 4, 3, 5, 1])

np.min(ar1) # np.int64(1)
np.max(ar1) # np.int64(5)

# 값이 여러개 있을 대 첫 번째 인덱스만 반환
np.argmin(ar1) # np.int64(0)
np.argmax(ar1) # np.int64(3)

# 배열 원소를 오름차순 정렬하고 인덱스만 반환
np.argsort(ar1)
# array([0, 8, 4, 6, 2, 5, 1, 3, 7])

In [ ]:
# 배열에서 최대값, 최소값 개수 찾기
np.sum(ar1 == np.max(ar1)) # np.int64(2)
np.sum(ar1 == np.min(ar1)) # np.int64(2)

In [ ]:
# 함수 설명 및 코드 보기
??np.argsort

### 무작위 값 추출

In [ ]:
seed = 1

np.random.seed(seed)
np.random.rand()

In [ ]:
for i in range(5):
    np.random.seed(seed)
    print(np.random.randint(0, 5, 1))

In [ ]:
for i in range(10):
    lotto = np.random.choice(range(1,46), 6, replace=False)
    lotto = [i.item() for i in lotto]
    print(sorted(lotto))